[supabase]
url = "https://ldimcgupjkqgmxecrkea.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaW1jZ3VwamtxZ214ZWNya2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTczODYsImV4cCI6MjA2NTAzMzM4Nn0.v1-_5TbBae0GqfWr3-9El0uZbOeJgYAGYcPY-pdDMO0"